weights: C:\Users\statb\Desktop\model_optimizer\pruned.pt
cfg: ''
data: C:\Users\statb\Desktop\yolov7\data\visdrone\visdrone.yaml
hyp: C:\Users\statb\Desktop\model_optimizer\configs\hyp.finetune.yaml
epochs: 1
batch_size: 8
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 2
project: C:\Users\statb\Desktop\model_optimizer\runs\finetune
entity: null
name: pruned_finetune
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
freeze_bn: false
lr0: 0.0001
warmup_epochs: 1.0
warmup_bias_lr: 0.0001
evolve: false
world_size: 1
global_rank: -1
save_dir: C:\Users\statb\Desktop\model_optimizer\runs\finetune\pruned_finetune
total_batch_size: 8
